# Per-state content for /states/<xx>/ pages.
# cities: (name, zip, approx annual snowfall in inches — NOAA 1991-2020 normals, rounded)
# districts: largest public districts by enrollment (order approximate)
# announce: where closings are announced locally (station / outlet names only)
# rules: how the state counts instructional time and treats snow days (summary; districts vary)
# neighbors: state codes for the "nearby states" links

STATES = {
 "MI": dict(name="Michigan", tier="north",
   cities=[("Detroit","48226",33),("Grand Rapids","49503",75),("Lansing","48933",50),("Flint","48502",47),("Ann Arbor","48104",56),("Kalamazoo","49007",70),("Traverse City","49684",100),("Marquette","49855",150)],
   districts=["Detroit Public Schools Community District","Utica Community Schools","Dearborn Public Schools","Grand Rapids Public Schools","Ann Arbor Public Schools"],
   announce=["WXYZ and WDIV (Detroit)","WOOD TV and WZZM (West Michigan)","WNEM (Mid-Michigan)","WILX (Lansing)","district websites and robocalls"],
   rules="Michigan requires 180 days and 1,098 hours, but the first six cancelled days are forgiven automatically and districts can apply to waive three more. That cushion is why Michigan districts close without much hesitation early in the winter and get stricter in March.",
   neighbors=["OH","IN","WI","IL"]),
 "MN": dict(name="Minnesota", tier="north",
   cities=[("Minneapolis","55401",52),("St. Paul","55101",52),("Duluth","55802",90),("Rochester","55902",50),("St. Cloud","56301",45),("Mankato","56001",40),("Moorhead","56560",50)],
   districts=["Anoka-Hennepin Schools","St. Paul Public Schools","Minneapolis Public Schools","Rosemount-Apple Valley-Eagan","Osseo Area Schools"],
   announce=["WCCO, KSTP, KARE 11 and FOX 9 closings lists (Twin Cities)","KTTC (Rochester)","WDIO and KBJR (Duluth)","district e-learning notices"],
   rules="Minnesota has no statutory minimum number of school days, so districts set their own calendars and make-up rules. Most large districts have an approved e-learning plan and can switch to a remote day instead of cancelling, which is why Minnesota closes for cold as readily as for snow — the day is rarely lost outright.",
   neighbors=["WI","IA","ND","SD"]),
 "WI": dict(name="Wisconsin", tier="north",
   cities=[("Milwaukee","53202",47),("Madison","53703",52),("Green Bay","54301",50),("Eau Claire","54701",55),("La Crosse","54601",45),("Wausau","54401",60),("Kenosha","53140",40)],
   districts=["Milwaukee Public Schools","Madison Metropolitan School District","Kenosha Unified","Green Bay Area Public Schools","Racine Unified"],
   announce=["TMJ4 and WISN (Milwaukee)","WKOW and WISC (Madison)","WBAY and WFRV (Green Bay)","WEAU (Eau Claire)","district alerts"],
   rules="Wisconsin counts instructional hours rather than days (1,050 for elementary, 1,137 for secondary). Virtual instruction can count toward those hours, so many districts now run a remote day on a storm day rather than losing it, and make-up days are less common than they were a decade ago.",
   neighbors=["MN","MI","IL","IA"]),
 "IL": dict(name="Illinois", tier="north",
   cities=[("Chicago","60601",38),("Naperville","60540",37),("Rockford","61101",36),("Peoria","61602",25),("Champaign","61820",23),("Springfield","62701",20),("Joliet","60432",33)],
   districts=["Chicago Public Schools","Elgin Area School District U-46","Indian Prairie District 204","Rockford Public Schools 205","Plainfield District 202"],
   announce=["Emergency Closing Center (emergencyclosings.com)","WGN, ABC 7 and NBC 5 (Chicago)","WREX (Rockford)","WCIA (Champaign)","district text alerts"],
   rules="Illinois requires 176 instructional days and builds five emergency days into every calendar. Districts with an approved e-learning plan can use a remote day instead of an emergency day, and Chicago Public Schools in particular rarely closes — it treats a snow day as a last resort.",
   neighbors=["WI","IN","MO","IA","KY"]),
 "CO": dict(name="Colorado", tier="north",
   cities=[("Denver","80202",57),("Colorado Springs","80903",38),("Fort Collins","80521",50),("Boulder","80302",85),("Pueblo","81003",30),("Grand Junction","81501",20),("Aurora","80010",55)],
   districts=["Denver Public Schools","Jeffco Public Schools","Douglas County School District","Cherry Creek Schools","Aurora Public Schools"],
   announce=["9NEWS, Denver7 and FOX31 closings lists","KKTV and KOAA (Colorado Springs)","KREX (Grand Junction)","district websites"],
   rules="Colorado sets a minimum in hours (1,080 for secondary, 990 for elementary) and leaves snow-day decisions entirely to districts. Front Range districts build in a buffer and typically close for a foot-plus storm or an icy morning commute; mountain districts close far less for the same totals.",
   neighbors=["NE","KS","NM","UT","WY"]),
 "NY": dict(name="New York", tier="northeast",
   cities=[("New York City","10007",29),("Buffalo","14202",95),("Rochester","14604",100),("Syracuse","13202",125),("Albany","12207",60),("Hempstead (Long Island)","11550",25),("Binghamton","13901",80),("Yonkers","10701",30)],
   districts=["New York City Public Schools","Buffalo Public Schools","Rochester City School District","Yonkers Public Schools","Syracuse City School District"],
   announce=["schools.nyc.gov and NYC Schools notifications","WIVB and WGRZ (Buffalo)","WHEC and 13WHAM (Rochester)","WTEN and WNYT (Albany)","News 12 (Long Island and Westchester)"],
   rules="New York ties full state aid to 180 days, so districts schedule a few spare days and will take back a vacation day if a hard winter uses them up. New York City is the outlier: since 2020 it generally declares a remote instruction day instead of a traditional snow day.",
   neighbors=["PA","NJ","CT","MA","VT"]),
 "MA": dict(name="Massachusetts", tier="northeast",
   cities=[("Boston","02108",49),("Worcester","01608",65),("Springfield","01103",45),("Lowell","01852",55),("Pittsfield","01201",70),("Hyannis (Cape Cod)","02601",25),("New Bedford","02740",30)],
   districts=["Boston Public Schools","Springfield Public Schools","Worcester Public Schools","Brockton Public Schools","Lynn Public Schools"],
   announce=["WCVB, WBZ and NBC10 Boston closings lists","WWLP (Springfield)","Boston.com and MassLive closings pages","district robocalls"],
   rules="Massachusetts requires 180 days and asks districts to schedule 185. The state does not count remote learning toward the 180, so Massachusetts districts close outright for a storm and make the day up in June rather than going virtual.",
   neighbors=["NH","VT","NY","CT","RI"]),
 "PA": dict(name="Pennsylvania", tier="northeast",
   cities=[("Philadelphia","19107",23),("Pittsburgh","15222",44),("Erie","16501",100),("Harrisburg","17101",30),("Scranton","18503",45),("Allentown","18101",32),("State College","16801",45),("Lancaster","17602",28)],
   districts=["School District of Philadelphia","Pittsburgh Public Schools","Central Bucks School District","Allentown School District","Reading School District"],
   announce=["KDKA, WPXI and WTAE (Pittsburgh)","6abc and NBC10 (Philadelphia)","WNEP (Scranton/Wilkes-Barre)","WGAL and abc27 (Harrisburg)","WJET and Erie News Now"],
   rules="Pennsylvania requires 180 days or 900 (elementary) to 990 (secondary) hours. Since 2019-20 districts can use up to five Flexible Instructional Days — remote days that count — so a storm day is often an FID rather than a cancellation, especially in the east.",
   neighbors=["NY","NJ","OH","MD","WV","DE"]),
 "CT": dict(name="Connecticut", tier="northeast",
   cities=[("Hartford","06103",40),("New Haven","06510",30),("Bridgeport","06604",26),("Stamford","06901",28),("Waterbury","06702",38),("Norwich","06360",35),("Danbury","06810",40)],
   districts=["Hartford Public Schools","Bridgeport Public Schools","New Haven Public Schools","Waterbury Public Schools","Stamford Public Schools"],
   announce=["WTNH, WFSB and NBC Connecticut closings lists","district websites and ParentSquare"],
   rules="Connecticut requires 180 days and lets districts count remote learning days with state approval, so some districts go virtual on a storm day while others still cancel and add a day in June. Delays are common here because the morning commute drives the decision.",
   neighbors=["NY","MA","RI"]),
 "RI": dict(name="Rhode Island", tier="northeast",
   cities=[("Providence","02903",33),("Warwick","02886",32),("Cranston","02920",33),("Pawtucket","02860",34),("Woonsocket","02895",40),("Newport","02840",22),("Westerly","02891",25)],
   districts=["Providence Public Schools","Cranston Public Schools","Warwick Public Schools","Pawtucket School Department","Woonsocket Education Department"],
   announce=["WPRI and WJAR closings lists","Rhode Island Broadcasters Association","district alerts"],
   rules="Rhode Island requires 180 days. Since 2021 the state lets districts count virtual learning days, so a storm often becomes a remote day rather than a cancellation — but delays remain the most common call on marginal mornings.",
   neighbors=["MA","CT"]),
 "NJ": dict(name="New Jersey", tier="northeast",
   cities=[("Newark","07102",28),("Jersey City","07302",25),("Trenton","08608",23),("Morristown","07960",32),("Toms River","08753",18),("Atlantic City","08401",16),("New Brunswick","08901",25)],
   districts=["Newark Public Schools","Jersey City Public Schools","Paterson Public Schools","Elizabeth Public Schools","Edison Township Public Schools"],
   announce=["News 12 New Jersey","NJ.com closings pages","district websites and alerts"],
   rules="New Jersey requires 180 days, and a 2020 law lets districts count virtual or remote days taken during an emergency closure. Many districts now keep one or two traditional snow days and switch to remote after that.",
   neighbors=["NY","PA","DE"]),
 "OH": dict(name="Ohio", tier="midwest",
   cities=[("Columbus","43215",22),("Cleveland","44114",64),("Cincinnati","45202",22),("Toledo","43604",35),("Akron","44308",47),("Dayton","45402",25),("Youngstown","44503",60),("Lima","45801",28)],
   districts=["Columbus City Schools","Cleveland Metropolitan School District","Cincinnati Public Schools","Toledo Public Schools","Akron Public Schools"],
   announce=["10TV and NBC4 (Columbus)","WKYC and FOX 8 (Cleveland)","WLWT and WCPO (Cincinnati)","WHIO and WDTN (Dayton)","WKBN (Youngstown)","WLIO (Lima)","WTOL (Toledo)"],
   rules="Ohio stopped counting calamity days in 2014 and now sets minimums in hours (910 for K-6, 1,001 for grades 7-12). Most districts schedule well above the minimum, so a closure rarely has to be made up — one reason Ohio districts close readily. Blizzard bags and remote days can cover extra closures.",
   neighbors=["MI","IN","KY","WV","PA"]),
 "MO": dict(name="Missouri", tier="midwest",
   cities=[("St. Louis","63101",18),("Kansas City","64106",15),("Springfield","65806",15),("Columbia","65201",17),("St. Joseph","64501",22),("Joplin","64801",10),("Cape Girardeau","63701",8)],
   districts=["Springfield Public Schools","St. Louis Public Schools","Kansas City Public Schools","Rockwood School District","Fort Zumwalt School District"],
   announce=["KSDK and KMOV (St. Louis)","KMBC and KSHB (Kansas City)","KY3 (Springfield)","KOMU (Columbia)","district alerts"],
   rules="Missouri counts 1,044 instructional hours. Districts can use up to 36 hours of Alternative Methods of Instruction (AMI) — remote packets or online days — before they must make up time, so a Missouri snow day is often an AMI day.",
   neighbors=["IL","KS","IA","KY","TN","AR","NE","OK"]),
 "IN": dict(name="Indiana", tier="midwest",
   cities=[("Indianapolis","46204",26),("Fort Wayne","46802",33),("South Bend","46601",65),("Evansville","47708",12),("Gary","46402",40),("Lafayette","47901",25),("Bloomington","47404",20)],
   districts=["Indianapolis Public Schools","Fort Wayne Community Schools","Evansville Vanderburgh School Corporation","Hamilton Southeastern Schools","Carmel Clay Schools"],
   announce=["WTHR and WISH-TV (Indianapolis)","WANE and WOWO (Fort Wayne)","WSBT (South Bend)","WEHT and 14 News (Evansville)"],
   rules="Indiana requires 180 days and counts eLearning days when a district's plan is approved, which nearly every district now has. A closure usually becomes an eLearning day, and a traditional cancelled day has to be made up at the end of the year.",
   neighbors=["MI","OH","KY","IL"]),
 "MD": dict(name="Maryland", tier="midatlantic",
   cities=[("Baltimore","21202",20),("Frederick","21701",25),("Hagerstown","21740",30),("Annapolis","21401",15),("Columbia","21044",20),("Salisbury","21801",8),("Cumberland","21502",35)],
   districts=["Montgomery County Public Schools","Prince George's County Public Schools","Baltimore County Public Schools","Baltimore City Public Schools","Anne Arundel County Public Schools"],
   announce=["WBAL and WJZ (Baltimore)","WTOP (DC suburbs)","county school system websites and alerts"],
   rules="Maryland requires 180 days and expects districts to build make-up days into the calendar; virtual days need state approval. The Montgomery and Prince George's decisions are watched statewide because they move with the federal government's operating status.",
   neighbors=["PA","DE","VA","WV","DC"]),
 "VA": dict(name="Virginia", tier="midatlantic",
   cities=[("Richmond","23219",10),("Arlington","22201",14),("Virginia Beach","23451",6),("Roanoke","24011",20),("Charlottesville","22902",15),("Winchester","22601",22),("Fredericksburg","22401",14)],
   districts=["Fairfax County Public Schools","Prince William County Public Schools","Loudoun County Public Schools","Virginia Beach City Public Schools","Chesterfield County Public Schools"],
   announce=["WTOP (Northern Virginia)","WRIC and WTVR (Richmond)","WAVY and WVEC (Hampton Roads)","WDBJ (Roanoke)"],
   rules="Virginia requires 180 days or 990 hours and lets districts take up to ten unscheduled remote learning days a year, so many large districts switch to virtual on a storm day. Northern Virginia's big districts close for totals that Richmond and Hampton Roads would see once a decade.",
   neighbors=["MD","WV","NC","TN","KY","DC"]),
 "DC": dict(name="Washington, DC", tier="midatlantic",
   cities=[("Washington (downtown)","20004",14),("Washington (Northwest)","20011",14),("Washington (Southeast)","20019",14)],
   districts=["DC Public Schools","DC public charter schools"],
   announce=["DCPS website and alerts","WTOP","the federal government's OPM operating status"],
   rules="DC Public Schools follows a 180-day calendar and, since 2020, usually declares a virtual learning day rather than a full closure. Charter schools decide independently, so the city can have a mix of open, virtual and closed schools on the same morning.",
   neighbors=["MD","VA"]),
 "WV": dict(name="West Virginia", tier="midatlantic",
   cities=[("Charleston","25301",30),("Huntington","25701",22),("Morgantown","26505",50),("Wheeling","26003",35),("Beckley","25801",60),("Parkersburg","26101",25),("Martinsburg","25401",25)],
   districts=["Kanawha County Schools","Berkeley County Schools","Monongalia County Schools","Cabell County Schools","Wood County Schools"],
   announce=["WSAZ and WCHS (Charleston/Huntington)","WBOY (Clarksburg)","WVDE county status page","county school websites"],
   rules="West Virginia requires 180 instructional days and can approve up to five non-traditional instruction (NTI) days; beyond that, closures are made up. Because every county is one district, a single call closes every school in the county, and mountain counties close far more often than the river valleys.",
   neighbors=["OH","PA","MD","VA","KY"]),
 "KY": dict(name="Kentucky", tier="south_border",
   cities=[("Louisville","40202",12),("Lexington","40507",13),("Covington","41011",20),("Bowling Green","42101",8),("Owensboro","42301",10),("Paducah","42001",8),("Pikeville","41501",20)],
   districts=["Jefferson County Public Schools","Fayette County Public Schools","Boone County Schools","Kenton County School District","Warren County Public Schools"],
   announce=["WLKY, WAVE 3 and WHAS (Louisville)","WKYT and LEX 18 (Lexington)","WBKO (Bowling Green)","district NTI announcements"],
   rules="Kentucky requires 170 days or 1,062 hours and allows up to ten non-traditional instruction (NTI) days, so a snow day usually becomes an NTI day with work sent home. Jefferson County went remote seven times in 2025-26 and closed outright only twice.",
   neighbors=["OH","IN","IL","MO","TN","VA","WV"]),
 "TN": dict(name="Tennessee", tier="south",
   cities=[("Nashville","37203",5),("Memphis","38103",3),("Knoxville","37902",6),("Chattanooga","37402",3),("Johnson City","37601",15),("Clarksville","37040",6),("Murfreesboro","37130",5)],
   districts=["Memphis-Shelby County Schools","Metro Nashville Public Schools","Knox County Schools","Hamilton County Schools","Rutherford County Schools"],
   announce=["WSMV and WKRN (Nashville)","WBIR and WATE (Knoxville)","WREG and Action News 5 (Memphis)","WCYB (Tri-Cities)"],
   rules="Tennessee requires 180 days and lets districts bank up to 13 'stockpile' days of extra instructional time to cover closures without make-up days. Remote days are capped, so districts close outright, and most use several of those stockpile days in a normal winter.",
   neighbors=["KY","VA","NC","GA","AL","MO","AR"]),
 "NC": dict(name="North Carolina", tier="south",
   cities=[("Charlotte","28202",4),("Raleigh","27601",5),("Greensboro","27401",7),("Winston-Salem","27101",7),("Asheville","28801",10),("Boone","28607",35),("Durham","27701",5)],
   districts=["Wake County Public School System","Charlotte-Mecklenburg Schools","Guilford County Schools","Winston-Salem/Forsyth County Schools","Cumberland County Schools"],
   announce=["WRAL (Raleigh)","WSOC and WCNC (Charlotte)","WFMY (Greensboro)","WLOS (Asheville)"],
   rules="North Carolina requires 185 days or 1,025 hours, and the state allows a limited number of remote instruction days. Districts in the Piedmont and coast close for an inch or for freezing rain; mountain districts have a higher tolerance and more make-up days built in.",
   neighbors=["VA","TN","GA","SC"]),
 "GA": dict(name="Georgia", tier="south",
   cities=[("Atlanta","30303",2),("Athens","30601",2),("Augusta","30901",1),("Macon","31201",1),("Rome","30161",2),("Gainesville","30501",2),("Columbus","31901",1)],
   districts=["Gwinnett County Public Schools","Cobb County School District","DeKalb County School District","Fulton County Schools","Atlanta Public Schools"],
   announce=["WSB-TV, 11Alive and FOX 5 (Atlanta)","WRDW (Augusta)","WMAZ (Macon)","district alerts"],
   rules="Georgia requires 180 days and lets districts make up closures with virtual days. Metro Atlanta districts close ahead of forecast ice — the 2014 gridlock storm shaped the policy — and a half-inch of freezing rain closes schools that a dusting of snow would not.",
   neighbors=["NC","SC","TN","AL"]),
 "TX": dict(name="Texas", tier="south",
   cities=[("Dallas","75201",2),("Fort Worth","76102",2),("Amarillo","79101",17),("Lubbock","79401",9),("Austin","78701",1),("El Paso","79901",4),("Houston","77002",0)],
   districts=["Houston ISD","Dallas ISD","Cypress-Fairbanks ISD","Northside ISD","Fort Worth ISD"],
   announce=["WFAA and KXAS (Dallas-Fort Worth)","KHOU (Houston)","KSAT (San Antonio)","KAMR and KVII (Amarillo)","district alerts"],
   rules="Texas measures the year in minutes (75,600) and requires two bad-weather make-up days in every calendar. Ice, not snow, closes Texas schools: a glaze on overpasses can shut a district from Dallas to Austin, while Amarillo and Lubbock run on several inches.",
   neighbors=["OK","NM","AR"]),
 # ---- added states ----
 "NH": dict(name="New Hampshire", tier="north",
   cities=[("Manchester","03101",60),("Nashua","03060",55),("Concord","03301",60),("Portsmouth","03801",50),("Keene","03431",65),("Berlin","03570",90),("Dover","03820",55)],
   districts=["Manchester School District","Nashua School District","Concord School District","Derry Cooperative School District","Bedford School District"],
   announce=["WMUR closings list","district alerts and local radio"],
   rules="New Hampshire requires 180 days and, after 2021, allows remote instruction days to count under state rules. Most districts still take traditional snow days first and add make-up days in June, so a late-winter storm is more likely to mean a delay than a closure.",
   neighbors=["ME","VT","MA"]),
 "VT": dict(name="Vermont", tier="north",
   cities=[("Burlington","05401",80),("Montpelier","05602",85),("Rutland","05701",70),("Brattleboro","05301",60),("St. Johnsbury","05819",85),("Bennington","05201",65)],
   districts=["Burlington School District","Champlain Valley School District","South Burlington School District","Essex Westford School District","Rutland City Public Schools"],
   announce=["WCAX and WPTZ closings lists","Vermont Public","district alerts"],
   rules="Vermont requires 175 days and lets districts count remote days with approval. Vermont schools run on serious snow, so closures tend to come from ice, a storm timed for the bus run, or deep cold rather than the totals that would close a southern state.",
   neighbors=["NH","NY","MA"]),
 "ME": dict(name="Maine", tier="north",
   cities=[("Portland","04101",65),("Lewiston","04240",70),("Bangor","04401",65),("Augusta","04330",70),("Presque Isle","04769",100),("Caribou","04736",110),("Brunswick","04011",65)],
   districts=["Portland Public Schools","Lewiston Public Schools","Bangor School Department","RSU 1 (Bath)","Auburn School Department"],
   announce=["News Center Maine, WMTW and WGME closings lists","district alerts"],
   rules="Maine requires 175 days and counts remote learning days under state rules, though many districts still cancel outright. Northern Maine districts run through snowfall that would close most of the country; coastal districts close for ice and for nor'easters that arrive at bus time.",
   neighbors=["NH"]),
 "IA": dict(name="Iowa", tier="north",
   cities=[("Des Moines","50309",35),("Cedar Rapids","52401",32),("Davenport","52801",30),("Sioux City","51101",32),("Iowa City","52240",28),("Waterloo","50701",33),("Dubuque","52001",38)],
   districts=["Des Moines Public Schools","Cedar Rapids Community School District","Davenport Community Schools","Iowa City Community School District","Sioux City Community School District"],
   announce=["KCCI and WHO 13 (Des Moines)","KCRG (Cedar Rapids)","KWQC (Quad Cities)","KTIV (Sioux City)"],
   rules="Iowa requires 1,080 hours or 180 days, and a 2021 law lets districts count online learning days, so a snow day is often a remote day. Wind and drifting matter as much as totals: a few inches with a 40 mph wind closes rural Iowa districts because the buses cannot run.",
   neighbors=["MN","WI","IL","MO","NE","SD"]),
 "NE": dict(name="Nebraska", tier="north",
   cities=[("Omaha","68102",27),("Lincoln","68508",26),("Grand Island","68801",28),("Kearney","68845",28),("North Platte","69101",30),("Scottsbluff","69361",40),("Norfolk","68701",30)],
   districts=["Omaha Public Schools","Lincoln Public Schools","Millard Public Schools","Papillion-La Vista Community Schools","Elkhorn Public Schools"],
   announce=["KETV and WOWT (Omaha)","KOLN/KGIN 10/11 (Lincoln)","district alerts"],
   rules="Nebraska sets minimums in hours (1,032 for elementary, 1,080 for secondary) and leaves closures to districts. Omaha and Lincoln close for a heavy storm or dangerous wind chill, and the western districts for blizzards that close the Interstate.",
   neighbors=["IA","KS","SD","CO","MO","WY"]),
 "KS": dict(name="Kansas", tier="midwest",
   cities=[("Wichita","67202",13),("Overland Park","66204",15),("Topeka","66603",17),("Lawrence","66044",16),("Salina","67401",15),("Garden City","67846",18),("Manhattan","66502",17)],
   districts=["Wichita Public Schools USD 259","Olathe Public Schools USD 233","Shawnee Mission School District","Blue Valley School District","Kansas City Kansas Public Schools USD 500"],
   announce=["KWCH and KSN (Wichita)","WIBW and KSNT (Topeka)","KMBC and KSHB (Kansas City metro)","district alerts"],
   rules="Kansas requires 1,116 hours and leaves snow days to districts, most of which schedule a few extra days. The Kansas City suburbs close for ice and for a six-inch storm; Wichita and the western districts tolerate more snow but close for blizzard conditions and extreme cold.",
   neighbors=["MO","NE","OK","CO"]),
 "SD": dict(name="South Dakota", tier="north",
   cities=[("Sioux Falls","57104",40),("Rapid City","57701",45),("Aberdeen","57401",38),("Pierre","57501",35),("Brookings","57006",40),("Watertown","57201",38)],
   districts=["Sioux Falls School District","Rapid City Area Schools","Harrisburg School District","Brandon Valley School District","Aberdeen Public Schools"],
   announce=["KELO and Dakota News Now (Sioux Falls)","KOTA and KEVN (Rapid City)","district alerts"],
   rules="South Dakota sets a minimum in hours and leaves closures to districts. Blizzard warnings and wind chills below -30°F drive most closures; the snow total on its own rarely does.",
   neighbors=["ND","MN","IA","NE","MT","WY"]),
 "ND": dict(name="North Dakota", tier="north",
   cities=[("Fargo","58102",50),("Bismarck","58501",50),("Grand Forks","58201",45),("Minot","58701",45),("Williston","58801",40),("Dickinson","58601",40)],
   districts=["Fargo Public Schools","Bismarck Public Schools","West Fargo Public Schools","Grand Forks Public Schools","Minot Public Schools"],
   announce=["Valley News Live and WDAY (Fargo)","KFYR (Bismarck)","KXMC (Minot)","district alerts"],
   rules="North Dakota requires 175 days and since 2021 lets districts run virtual instruction days instead of closing. Blizzards and -40°F wind chills close schools; snowfall totals that would stop the East Coast do not.",
   neighbors=["SD","MN","MT"]),
 "MT": dict(name="Montana", tier="north",
   cities=[("Billings","59101",55),("Missoula","59801",40),("Great Falls","59401",60),("Bozeman","59715",70),("Helena","59601",45),("Butte","59701",55),("Kalispell","59901",60)],
   districts=["Billings Public Schools","Great Falls Public Schools","Missoula County Public Schools","Bozeman Public Schools","Helena Public Schools"],
   announce=["KTVQ and KULR (Billings)","KPAX (Missoula)","KRTV (Great Falls)","district alerts"],
   rules="Montana requires 1,080 hours and leaves closures to districts, which rarely close for snow alone. Dangerous wind chill, ice on the mountain passes and blizzard conditions that stop the buses are the usual reasons.",
   neighbors=["ND","SD","ID","WY"]),
 "ID": dict(name="Idaho", tier="north",
   cities=[("Boise","83702",18),("Idaho Falls","83402",35),("Pocatello","83201",45),("Coeur d'Alene","83814",50),("Twin Falls","83301",15),("Lewiston","83501",15),("Nampa","83651",18)],
   districts=["West Ada School District","Boise School District","Nampa School District","Bonneville Joint School District","Idaho Falls School District 91"],
   announce=["KTVB and KIVI (Boise)","KIFI and KIDK (Idaho Falls)","KREM and KHQ (Coeur d'Alene/Spokane)","district alerts"],
   rules="Idaho sets a minimum in hours (990 for most grades) and leaves closures to districts. The Treasure Valley closes for an icy commute or a rare heavy storm; eastern Idaho and the Panhandle close mainly for wind chill and road closures.",
   neighbors=["MT","WA","OR","UT","NV","WY"]),
 "UT": dict(name="Utah", tier="north",
   cities=[("Salt Lake City","84111",56),("Provo","84601",50),("Ogden","84401",60),("Logan","84321",55),("Park City","84060",150),("St. George","84770",2),("Cedar City","84720",45)],
   districts=["Alpine School District","Davis School District","Granite School District","Jordan School District","Canyons School District"],
   announce=["KSL, KUTV and FOX 13 (Salt Lake)","district alerts"],
   rules="Utah requires 180 days or 990 hours and lets districts run remote days. Wasatch Front districts almost never close for snow — the 2023 record winter produced a handful of closures — and when they do it is for an overnight dump that beats the plows to the morning commute.",
   neighbors=["ID","CO","NM","NV","WY"]),
 "WA": dict(name="Washington", tier="south",
   cities=[("Seattle","98101",6),("Spokane","99201",45),("Tacoma","98402",6),("Bellingham","98225",10),("Yakima","98901",22),("Wenatchee","98801",35),("Vancouver","98660",5)],
   districts=["Seattle Public Schools","Spokane Public Schools","Lake Washington School District","Tacoma Public Schools","Kent School District"],
   announce=["FlashAlert Seattle and FlashAlert Spokane","KING 5 and KOMO (Seattle)","KREM and KHQ (Spokane)"],
   rules="Washington requires 180 days and 1,027 hours and expects closures to be made up, which is why Puget Sound districts add days in June after a snowy winter. Seattle closes for an inch or two because of hills and ice; Spokane runs on far more and closes for extreme cold.",
   neighbors=["OR","ID"]),
 "OR": dict(name="Oregon", tier="south",
   cities=[("Portland","97204",4),("Salem","97301",5),("Eugene","97401",5),("Bend","97701",25),("Medford","97501",5),("Klamath Falls","97601",35),("Hillsboro","97123",4)],
   districts=["Portland Public Schools","Salem-Keizer Public Schools","Beaverton School District","Hillsboro School District","Bend-La Pine Schools"],
   announce=["FlashAlert Portland","KGW and KOIN (Portland)","KEZI and KVAL (Eugene)","KTVZ (Bend)"],
   rules="Oregon sets a minimum in hours and requires missed time to be made up, so Portland-area districts avoid closing when they can delay. An inch of snow or an ice storm in the Willamette Valley closes schools; Bend and Klamath Falls run on a foot.",
   neighbors=["WA","ID","NV"]),
 "OK": dict(name="Oklahoma", tier="south",
   cities=[("Oklahoma City","73102",7),("Tulsa","74103",10),("Norman","73069",7),("Lawton","73501",5),("Enid","73701",10),("Stillwater","74074",8),("Broken Arrow","74012",10)],
   districts=["Oklahoma City Public Schools","Tulsa Public Schools","Edmond Public Schools","Moore Public Schools","Broken Arrow Public Schools"],
   announce=["KOCO and KFOR (Oklahoma City)","News On 6 and KJRH (Tulsa)","district alerts"],
   rules="Oklahoma requires 180 days or 1,080 hours and allows virtual days, which most metro districts now use instead of cancelling. Ice is the closer: a quarter-inch of freezing rain shuts districts from Lawton to Tulsa, while a dry two-inch snow often brings only a delay.",
   neighbors=["TX","KS","MO","AR","NM","CO"]),
 "AR": dict(name="Arkansas", tier="south",
   cities=[("Little Rock","72201",4),("Fayetteville","72701",7),("Fort Smith","72901",5),("Jonesboro","72401",6),("Hot Springs","71901",4),("Harrison","72601",10),("Conway","72032",4)],
   districts=["Little Rock School District","Springdale Public Schools","Bentonville Public Schools","Rogers Public Schools","Fort Smith Public Schools"],
   announce=["KATV and THV11 (Little Rock)","KNWA and 40/29 (Northwest Arkansas)","KAIT (Jonesboro)"],
   rules="Arkansas requires 178 days and lets districts use up to ten Alternative Methods of Instruction (AMI) days, so a winter-weather closure is usually an AMI day with work sent home. A dusting of snow or any ice closes most districts; the Ozarks tolerate a little more.",
   neighbors=["MO","TN","OK","TX","LA","MS"]),
 "DE": dict(name="Delaware", tier="midatlantic",
   cities=[("Wilmington","19801",20),("Newark","19711",18),("Middletown","19709",16),("Dover","19901",13),("Rehoboth Beach","19971",8),("Seaford","19973",8)],
   districts=["Christina School District","Red Clay Consolidated School District","Appoquinimink School District","Brandywine School District","Capital School District"],
   announce=["WDEL closings list","Delaware Online","district alerts"],
   rules="Delaware requires 180 days and expects closures to be made up, so districts schedule a few spare days. New Castle County closes for the same storms that close Philadelphia's suburbs; Sussex County sees snow less often and closes for less of it.",
   neighbors=["MD","PA","NJ"]),
 "NM": dict(name="New Mexico", tier="south",
   cities=[("Albuquerque","87102",9),("Santa Fe","87501",30),("Las Cruces","88001",3),("Farmington","87401",10),("Roswell","88201",6),("Taos","87571",35),("Rio Rancho","87124",9)],
   districts=["Albuquerque Public Schools","Las Cruces Public Schools","Rio Rancho Public Schools","Santa Fe Public Schools","Gadsden Independent School District"],
   announce=["KOB, KRQE and KOAT (Albuquerque)","district alerts"],
   rules="New Mexico requires 180 days and expects closures to be made up, though Albuquerque Public Schools more often calls a two-hour delay than a closure. Ice and an overnight storm on the morning commute close Albuquerque; Santa Fe and Taos run on much more snow.",
   neighbors=["CO","TX","OK","AZ","UT"]),
 "SC": dict(name="South Carolina", tier="south",
   cities=[("Columbia","29201",1),("Greenville","29601",4),("Charleston","29401",0),("Spartanburg","29301",4),("Rock Hill","29730",3),("Myrtle Beach","29577",0)],
   districts=["Greenville County Schools","Charleston County School District","Horry County Schools","Berkeley County School District","Richland School District Two"],
   announce=["WIS (Columbia)","WYFF (Greenville)","WCSC and WCBD (Charleston)","district alerts"],
   rules="South Carolina requires 180 days and builds three make-up days into every calendar, with eLearning days allowed as make-up. Any accumulating snow or freezing rain closes schools across the state; the Upstate sees it a few times a winter, the coast rarely.",
   neighbors=["NC","GA"]),
 "AL": dict(name="Alabama", tier="south",
   cities=[("Birmingham","35203",2),("Huntsville","35801",3),("Montgomery","36104",0),("Tuscaloosa","35401",1),("Mobile","36602",0),("Florence","35630",3)],
   districts=["Mobile County Public Schools","Jefferson County Schools","Baldwin County Public Schools","Montgomery Public Schools","Huntsville City Schools"],
   announce=["WBRC and WVTM (Birmingham)","WAFF and WHNT (Huntsville)","WSFA (Montgomery)","district alerts"],
   rules="Alabama requires 180 days and leaves make-up days to local boards. Forecast ice or a winter storm warning closes schools before the first flake — the January 2014 storm that stranded students overnight is why — so Alabama closes on the forecast, not on the ground.",
   neighbors=["TN","GA","MS","FL"]),
}

TIERS = {
  "north":        dict(label="Northern snow belt", s50=6.2, s80=11.1, cold=-35),
  "northeast":    dict(label="Northeast",          s50=5.2, s80=9.0,  cold=-16),
  "midwest":      dict(label="Midwest",            s50=2.8, s80=5.3,  cold=-11),
  "midatlantic":  dict(label="Mid-Atlantic",       s50=3.2, s80=4.9,  cold=-20),
  "south_border": dict(label="Border South",       s50=1.9, s80=3.1,  cold=-15),
  "south":        dict(label="South",              s50=1.0, s80=1.5,  cold=-15),
}

# Region explainer (one per tier), used once per page.
TIER_TEXT = {
  "north": "Districts here own the plows and the buses are built for it. A storm has to be big, badly timed or paired with wind and deep cold before schools close, and a six-inch overnight snowfall is often just a normal Tuesday.",
  "northeast": "Coastal storms drop heavy, wet snow fast. Districts tolerate a moderate storm but close for nor'easters, and a storm that arrives during the morning commute closes schools at a much lower snow total than the same storm overnight.",
  "midwest": "A middle case: enough equipment to handle a few inches, but closures come quickly once ice is involved or wind chill turns dangerous for children waiting at bus stops.",
  "midatlantic": "Snow is an event rather than a season. Districts close for a few inches, and freezing rain or a storm timed for the morning commute closes them for much less.",
  "south_border": "Snow is occasional and equipment is limited, so districts act early and often switch to a remote day rather than lose a calendar day.",
  "south": "A dusting is news. Districts have little equipment, bridges ice first, and most closures come from forecast ice rather than measured snow — many are announced the night before, on the forecast alone.",
}

# Season sentence per tier
SEASON = {
  "north": "Closures cluster from mid-December through February, with the first of the season usually in late November or early December and a few from late-season blizzards into March.",
  "northeast": "Most closures fall between late December and the end of February, driven by nor'easters; a late-March storm catches districts that have already used their spare days.",
  "midwest": "Closures run from December through February, with January the busiest month and ice storms responsible for many of them.",
  "midatlantic": "Most winters bring a handful of closures between January and mid-February; some winters bring none.",
  "south_border": "Expect one to three closures in a typical winter, almost all in January and early February, often as remote days.",
  "south": "Most winters bring one or two closure days, usually in January, and some winters none at all. Ice, not snow, is the usual reason.",
}
